name: CI

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  lint:
    name: Terraform lint & scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.7"

      - name: fmt check
        run: terraform fmt -check -recursive .

      - name: validate
        run: terraform init -backend=false && terraform validate

      - uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - name: tflint
        run: |
          tflint --init
          tflint --recursive --minimum-failure-severity=error

      - name: checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          config_file: .checkov.yaml
          quiet: true
          soft_fail: false
          framework: terraform
